"use client"

import { useEffect, useState } from "react"
import { useParams } from "next/navigation"
import { motion } from "framer-motion"
import { Radar } from "lucide-react"
import { ScoreOverview } from "@/components/report/ScoreOverview"
import { LayerCard } from "@/components/report/LayerCard"
import { RadarChart } from "@/components/report/RadarChart"
import { StrengthsWeaknesses } from "@/components/report/StrengthsWeaknesses"
import { Roadmap } from "@/components/report/Roadmap"
import { ReportCTA } from "@/components/report/CallToAction"
import type { AnalysisResult } from "@/types/analysis"
import { extractDomain } from "@/lib/utils"

export default function ReportPage() {
  const params = useParams()
  const id = params.id as string
  const [result, setResult] = useState<AnalysisResult | null>(null)
  const [loading, setLoading] = useState(true)
  const [error, setError] = useState<string | null>(null)

  useEffect(() => {
    async function fetchReport() {
      try {
        const response = await fetch(`/api/report/${id}`)
        if (!response.ok) {
          throw new Error(response.status === 404 ? "Report not found" : "Failed to load report")
        }
        const data = await response.json()
        setResult(data)
      } catch (err) {
        setError(err instanceof Error ? err.message : "Failed to load report")
      } finally {
        setLoading(false)
      }
    }
    fetchReport()
  }, [id])

  if (loading) {
    return (
      <div className="min-h-screen flex items-center justify-center pt-16">
        <div className="text-center">
          <div className="w-12 h-12 border-2 border-cyan-500 border-t-transparent rounded-full animate-spin mx-auto mb-4" />
          <p className="text-gray-400">Loading your report...</p>
        </div>
      </div>
    )
  }

  if (error || !result) {
    return (
      <div className="min-h-screen flex items-center justify-center pt-16">
        <div className="text-center max-w-md mx-auto px-4">
          <div className="w-16 h-16 rounded-full bg-red-500/10 border border-red-500/20 flex items-center justify-center mx-auto mb-4">
            <Radar className="h-8 w-8 text-red-400" />
          </div>
          <h1 className="text-xl font-bold text-white mb-2">Report Not Found</h1>
          <p className="text-gray-400 text-sm">{error || "This report may have expired or the URL is incorrect."}</p>
        </div>
      </div>
    )
  }

  return (
    <div className="min-h-screen pt-24 pb-16">
      <div className="mx-auto max-w-5xl px-4 sm:px-6 lg:px-8">
        {/* Header */}
        <motion.div
          className="text-center mb-8"
          initial={{ opacity: 0, y: 10 }}
          animate={{ opacity: 1, y: 0 }}
        >
          <div className="inline-flex items-center gap-2 rounded-full border border-cyan-500/20 bg-cyan-500/5 px-3 py-1 text-xs text-cyan-400 mb-4">
            <Radar className="h-3.5 w-3.5" />
            6-Layer Semantic Authority Report
          </div>
          <h1 className="text-2xl font-bold text-white mb-1">{extractDomain(result.url)}</h1>
          <p className="text-xs text-gray-500 font-mono">{result.url}</p>
        </motion.div>

        {/* Overall Score */}
        <ScoreOverview result={result} />

        {/* Radar Chart */}
        <div className="mb-12">
          <RadarChart layers={result.layerScores} />
        </div>

        {/* Layer-by-layer scores */}
        <div className="mb-12">
          <h2 className="text-lg font-semibold text-white mb-6 text-center">Layer-by-Layer Analysis</h2>
          <div className="space-y-4">
            {result.layerScores.map((layer, i) => (
              <LayerCard key={layer.layerNumber} layer={layer} index={i} />
            ))}
          </div>
        </div>

        {/* Strengths, Blockers, Quick Wins */}
        <div className="mb-12">
          <StrengthsWeaknesses result={result} />
        </div>

        {/* Roadmap */}
        <div className="mb-12">
          <Roadmap result={result} />
        </div>

        {/* CTA */}
        <ReportCTA />

        {/* Disclaimer */}
        <p className="text-xs text-gray-600 text-center mt-8 max-w-2xl mx-auto leading-relaxed">
          This report is generated by Holistic Radar&apos;s strategic interpretive framework for analyzing how modern search systems likely evaluate content. Scores and recommendations are based on observable signals and do not represent guaranteed ranking factors or official search engine algorithms.
        </p>
      </div>
    </div>
  )
}
